export { default as About } from './About'
export { default as Events } from './Events'
export { default as Contact } from './Contact'
export { default as Gallery } from './Gallery'
export { default as Menu } from './Menu'
export { default as Header } from './Header'