export { default as About } from './About'
export { default as Navbar } from './Navbar'
export { default as Footer } from './Footer'
export { default as Events } from './Events'
export { default as Contact } from './Contact'
export { default as Gallery } from './Gallery'
export { default as Menu } from './Menu'